#Default configuration for NarnaLinks
#Change the lists to your needs, you can add as many links to any command as you like. (For example like I did with vote)
#Use $ for colour codes instead of the usual &, this is done because & tends to be in a lot of URL's
site:
  - '$2sitelink'
vote:
  - votelink 1
  - votelink 2
donate:
  - donatelink
contact:
  - contactlink
dynmap:
  - dynmaplink
